### ISSUE TITLE
Cannot disable SSL verification

### ISSUE THREAD

**Issue by WoodrowShigeru** [xini/silverstripe-mailchimp-signup#3] opened 2018-12-12 15:40 UTC
`Config::inst()->update('DrewM\MailChimp\MailChimp', 'verify_ssl', false);`

This line mentioned in the documentation does not work because of a fatal error:

`ERROR [Emergency]: Uncaught Error: Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::update()`

The things I found about this problem (or rather: similar problems) imply that it's a dependency issue.

* https://github.com/silverstripe/silverstripe-framework/issues/6785
* https://github.com/Cyber-Duck/Silverstripe-SEO/issues/13
* https://github.com/silverstripe/silverstripe-installer/issues/167

Are you sure this add-on is compatible with SS4?

-----

Using PHP 7.2. Excerpt from my composer.json:
```
"silverstripe/recipe-cms": "4.2.2@stable",
"innoweb/silverstripe-mailchimp-signup": "dev-master"
```

**Comment by xini** [comment] 2018-12-13 04:54
Just tested with SS 4.2.3 and 4.3 and I can't reproduce the issue. The disabling seems to work as far as I can see? 
I'll close this for now, let me know if you keep having issues with this.

**Closed as completed by xini** 2018-12-13 04:54 UTC

**Comment by WoodrowShigeru** [comment] 2018-12-13 11:42
Strange. I'm not really depending on this (I don't think), but I definitely have an error here.

I can post the full composer.json here, if that makes a difference, but feel free to fix or ignore this as you please. No hard feelings.

```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.2.2@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/subsites": "^2.2",
        "undefinedoffset/sortablegridfield": "^2.0",
        "silverstripe/blog": "^3.2",
        "jonom/focuspoint": "^3.0",
        "wilr/silverstripe-googlesitemaps": "^2.1",
        "gorriecoe/silverstripe-robots": "^1.0",
        "innoweb/silverstripe-mailchimp-signup": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7"
    },
    "extra": {
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

**Comment by xini** [comment] 2018-12-13 22:22
Weird. Can't see anything out of the ordinary here. 
Can you try to upgrade to SS 4.2.3 or 4.3?
What PHP version is your server running on? My local for this one is on 7.2.
